apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  containers:
  - name: my-nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myVolume
      mountPath: "/my-folder/"
  volumes:
  - name: myVolume
    persistentVolumeClaim:
      claimName: $PVC_NAME